import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import {
  AtlassianNavigation,
  Create,
  CustomProductHome,
  PrimaryButton,
  SignIn,
} from '@atlaskit/atlassian-navigation';
import styles from '../styles/Home.module.css';

const CustomHome = () => (
  <CustomProductHome
    href="/"
    iconAlt={'DM'}
    iconUrl={
      'https://cdn-icons.flaticon.com/png/512/1442/premium/1442632.png?token=exp=1660856458~hmac=2dffa710d062a4fe2b412e31ce1a745a'
    }
    logoAlt={'DevMatch'}
    logoUrl={'https://i.ibb.co/JRh87FW/logo-1.png'}
    logoMaxWidth={300}
  />
);

const DefaultSignIn = () => <SignIn href="/signin" tooltip="Sign in" />;

const CustomRouterLink = (props: {
  children: React.ReactNode;
  href: string;
}) => (
  <Link href={props.href}>
    <a>{props.children}</a>
  </Link>
);

const CreateButton = () => <Create href="/signup" text="Create account" />;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AtlassianNavigation
        label="site"
        primaryItems={[
          <PrimaryButton
            component={CustomRouterLink}
            href={'item1'}
            key={'nav-item-1'}
          >
            Item 1
          </PrimaryButton>,
          <PrimaryButton
            component={CustomRouterLink}
            href={'item2'}
            isHighlighted={true}
            key={'nav-item-2'}
          >
            Item 2
          </PrimaryButton>,
          <PrimaryButton
            component={CustomRouterLink}
            href={'item3'}
            key={'nav-item-3'}
          >
            Item 3
          </PrimaryButton>,
        ]}
        renderCreate={CreateButton}
        renderProductHome={CustomHome}
        renderSignIn={DefaultSignIn}
      />
    </div>
  );
};

export default Home;
