import Button from '@atlaskit/button';
import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="w-full flex flex-col justify-center items-center h-96 text-slate-800">
        <h1 className="text-5xl font-medium">Lorem Ipsum</h1>
        <h2 className="text-3xl pt-1">
          Neque porro quisquam est qui dolorem ipsum quia dolor sit amet
        </h2>
        <div className="pt-5">
          <Button appearance="primary">Get started</Button>
        </div>
      </div>
    </div>
  );
};

export default Home;
